Incr8: comperssion
zueve/go-shortener pull request #6
Opened 2022-01-24 20:30 UTC by zueve

2022-01-27 19:32 UTC, iTiky requested changes
Нужны доработки + не учтены все мои комментарии из прошлого PR-а.

2022-01-27 19:32 UTC, iTiky commented on internal/config/context.go
> +type Context struct {
Это очень плохое имя для структуры. В Go Context это строго `context.Context`.

2022-01-27 19:32 UTC, iTiky commented on internal/config/context.go
> +	ctx             context.Context
Контекст никогда не должен быть внутри какого-либо состояния. Есть исключения, но здесь - это не оправдано (это точно не часть конфига).

2022-01-27 19:32 UTC, iTiky commented on internal/config/models.go
> +package config
Имя файла `models.go` сбивает с толку. Это не модели.

2022-01-27 19:32 UTC, iTiky commented on internal/config/models.go
> +	ServerAddress   string `env:"SERVER_ADDRESS" envDefault:":8080"`
Почему эти структурные тэги нельзя было добавить в структуру Context? Лишнее дублирование сущностей.

2022-01-27 19:32 UTC, iTiky commented on internal/config/context.go
> +func NewContextFromEnvAndCMD() *Context {
Возврат указателя ничем не оправдан. Конфиг должен быть иммутабелен.

2022-01-27 19:32 UTC, iTiky commented on internal/config/context.go
> +		panic(err)
Решение о панике должен принимать только главный тред. В данном случае необходимо вернуть ошибку.

2022-01-27 19:32 UTC, iTiky commented on internal/config/context.go
> +func NewContext(opts ...ContextOption) *Context {
Здорово, конечно, что ты применил этот паттерн, но здесь он лишний. Все поля этой структуры - публичны, их просто задать. Опции-сеттеры тут лишние.

2022-01-27 19:32 UTC, iTiky commented on internal/config/context.go
> +	baseURL := flag.String("b", envronment.BaseURL, "a string")
В данном варианте что имеет больший приоритет, ENV или flag? Флаги - это конфигурация CLI приложения. ENV-ы - это переопределение дефолтных значений. Иначе можно представить так: флаги - это Docker entrypoint, ENV-ы - это переменные Docker-а для настройки "под себя" и передачи секретов.

2022-01-27 19:32 UTC, iTiky commented on cmd/shortener/main.go
> +	storageVar := storage.New(persistentStorage)
Читая строку `server.New(ctx, serviceVar)`, я понимаю что в функцию передают `context.Context`, но у тебя этот стандартный Go-паттерн ломается.

2022-01-27 19:32 UTC, iTiky commented on internal/server/server.go
> +			s.error(w, http.StatusInternalServerError, "invalid parse body")
"invalid parse body" это не очень по-русски =) Я бы ещё добавил сюда саму ошибку `err`

2022-01-27 19:32 UTC, iTiky commented on internal/server/server.go
> +		err = json.Unmarshal(dataBytes, &redirect)
Уже писал об этом ранее. Лучше придерживаться Go-стиля:
```go
if err := json.Unmarshal(...); err != nil {}
```

2022-01-27 19:32 UTC, iTiky commented on internal/server/server_test.go
> +	os.Remove(filename)
Не во всех ОС есть /tmp. Можно воспользоваться stdlib-ой:
https://yourbasic.org/golang/temporary-file-directory/

2022-01-27 19:32 UTC, iTiky commented on internal/server/server_test.go
> +			data:        "{\"url\": \"http://example.com\"}",
Это не читабельно. Лучше прям в этой фукнции объявить тип и получать его JSON-репрезентацию:
```go
type request struct {
    Field string `json:"field"`
}

tests := []struct {
    data request
}{
    {
        data: request {
            Field: "bla bla"
        }
    }
}
```

2022-01-27 19:32 UTC, iTiky commented on internal/server/server_test.go
> +				t.Errorf("Expected status code %d, got %d", tt.code, w.Code)
Как я писал ранее, лучше изучать testify библиотеку, с ней тесты станут более читаемы и поддерживаемы.
Эта строка будет выглядеть так:
```go
require.Equal(t, tt.code, res.StatusCode)
```

2022-01-27 19:32 UTC, iTiky commented on internal/storage/storage.go
> +		panic(err)
Необходимо вернуть ошибку, но не паниковать.

2022-01-27 19:32 UTC, iTiky commented on internal/storage/storage.go
> +type PersistentStorage interface {
Имя сбивает с толку. Мне показалось, что ты объявил интерфейс, а ниже - его имплементация. Если ожидаемый контракт для зависимости, лучше его именовать как `PersistentStorageExpected`.

2022-01-27 19:32 UTC, iTiky commented on internal/storage/file.go
> +		log.Fatal(err)
Почему не возврат ошибки, а падение? Кроме того, в одном месте у тебя Fatal, в другом - паника. В обоих случаях должен быть возврат ошибки.

2022-01-28 09:34 UTC, zueve commented on internal/config/context.go
> +type Context struct {
Согласен, но именно так описано в статье, на которую ты мне указал в прошлый раз https://medium.com/star-gazers/go-options-pattern-da49185a2526

2022-01-28 09:34 UTC, zueve commented on internal/config/context.go
> +	ctx             context.Context
Тоже самое https://medium.com/star-gazers/go-options-pattern-da49185a2526

2022-01-28 09:36 UTC, zueve commented on internal/config/models.go
> +	ServerAddress   string `env:"SERVER_ADDRESS" envDefault:":8080"`
Прока можно, но представление в env может отличаться от других, и когда-нибудь их придется разделять

2022-01-28 09:37 UTC, zueve commented on internal/config/context.go
> +func NewContextFromEnvAndCMD() *Context {
Тоже самое https://medium.com/star-gazers/go-options-pattern-da49185a2526

2022-01-28 09:42 UTC, zueve commented on internal/config/context.go
> +	baseURL := flag.String("b", envronment.BaseURL, "a string")
тут не согласен. Флаги первичнее! Когда пишешь команду add -s 123 - ожидаешь что s всегда будет 123 независимо от параметров среду, которые вообще могут быть определены глобально, и даже иметь конфликты с приложением

2022-01-28 09:43 UTC, zueve commented on cmd/shortener/main.go
> +	storageVar := storage.New(persistentStorage)
Тоже самое https://medium.com/star-gazers/go-options-pattern-da49185a2526

2022-01-28 09:45 UTC, zueve commented on internal/server/server.go
> +			s.error(w, http.StatusInternalServerError, "invalid parse body")
A я бы не стал прокидывать наружу неизвестную информацию. В логах ок

2022-01-28 09:50 UTC, zueve commented on internal/server/server.go
> +		err = json.Unmarshal(dataBytes, &redirect)
Если честно, не нашел где ты на это указывал. В коде я такое сокращение встречал, но оно мне как-то дико не нравится.

2022-01-28 09:53 UTC, zueve commented on internal/server/server_test.go
> +				t.Errorf("Expected status code %d, got %d", tt.code, w.Code)
Да как-то нет времени изучать...

2022-02-02 20:58 UTC, iTiky approved these changes
✔️

2022-02-02 20:58 UTC, iTiky commented on internal/server/server_test.go
> +		return TestServer{}, err
Testify: `require.NoError(t, err)`
С помощью этой либы будет куда читабельнее.

2022-02-03 13:17 UTC, merged